### ISSUE TITLE
Allow to export/import filters

### ISSUE THREAD

**Issue by licoffe** [licoffe/POE-sniper#10] opened 2017-06-21 07:53 UTC

**Comment by gdneye** [comment] 2017-07-12 20:49
Feature Request

Hey Licoffe, I've been out of town for a bit over a week, so apologies for not closing out old tickets.  I'm back and downloaded the latest version.  The new features are nice and so far the program seems to be running more smoothly.  I really like the import filter function, but noticed that it doesn't import the price from the filter. This isn't huge, and may be by design, but my personal preference would be to include the price in the import as I am currently importing the filter, then adding the price.

Regardless, thanks for building a really nice sniping tool.

**Comment by licoffe** [comment] 2017-07-13 15:12
I'm already importing the max price from poe.trade as you can see [here](https://www.youtube.com/watch?v=Qcji2xcboPQ&index=1&list=UU0DCSDjvKsoaZt7Uy0MuwOg) but it looks like I introduced some regression by mistake :(

**Comment by gdneye** [comment] 2017-07-13 15:21
Interesting... not sure what I'm doing wrong here...

https://youtu.be/EPyTqxXb8DM

Sorry for the crap quality, I'm going to learn how to upload in hd right now.

**Comment by licoffe** [comment] 2017-07-13 15:24
It's not on your side :) I introduced some regression by mistake in the code. Changed something, probably to add a feature and it broke some other functions. I'm investigating it.

**Comment by licoffe** [comment] 2017-07-13 15:56
I found the culprit. For some reason "data.buyout_max" became "data.buyout.max" and it just stopped working XD It will be fixed in the next release and there will definitely be a release before the next race tomorrow.

**Closed as completed** 2017-07-16 13:55 UTC
Labels: Feature
